import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const read=p=>JSON.parse(readFileSync(p,'utf8'));
const catalog=read('data/exercise_catalog.json'); const progress=read('reports/catalog_curation_progress.json');
const worker=[...read('staging/worker_batch002.json').results,...read('staging/worker_batch003.json').items,...read('staging/worker_batch004.json').records];
const grouped=Map.groupBy(worker,x=>x.mediaId??x.id); const overlaps=[...grouped].filter(([,v])=>v.length>1); const selected=[...grouped.values()].map(v=>v.sort((a,b)=>Number(Boolean(b.canonicalNameEn))-Number(Boolean(a.canonicalNameEn)))[0]); const ids=new Set(selected.map(x=>x.mediaId??x.id));
const byId=new Map(catalog.exercises.map(x=>[x.id,x])); let high=0,medium=0,low=0;
for(const r of selected){const id=r.mediaId??r.id,e=byId.get(id);if(!e)throw Error(`missing ${id}`); const confidence=r.confidence; if(confidence==='HIGH')high++;else if(confidence==='MEDIUM')medium++;else low++; Object.assign(e,{namePtBr:r.namePtBr,canonicalNameEn:r.canonicalNameEn,aliases:r.aliasesPtBr??[],description:r.description,instructions:r.executionSteps??r.instructions,primaryMuscles:r.primaryMuscles,secondaryMuscles:r.secondaryMuscles,equipment:r.equipment,bodyRegion:r.bodyRegions??r.bodyRegion,movementPattern:r.movementPattern,exerciseType:r.exerciseType??r.type,difficulty:r.difficulty,laterality:r.laterality,position:r.position,environment:r.environments??r.environment,tags:r.tags,commonMistakes:r.commonErrors??r.commonMistakes,safetyNotes:r.safetyNotes,confidence,identificationStatus:'curated',needsManualReview:confidence==='LOW'});}
progress.processed=1+selected.length;progress.remaining=progress.totalMedia-progress.processed;progress.highConfidence=1+high;progress.mediumConfidence=medium;progress.lowConfidence=low;progress.manualReview=low;progress.animatedProcessed=progress.processed;progress.currentBatch=4;progress.lastProcessedMediaId=selected.at(-1).mediaId??selected.at(-1).id;progress.nextMediaId='pending_after_worker_batch004';progress.completedMediaIds=[...new Set([...progress.completedMediaIds,...ids])];progress.updatedAt=new Date().toISOString();
mkdirSync('reports',{recursive:true});writeFileSync('data/exercise_catalog.json',JSON.stringify(catalog,null,2)+'\n');writeFileSync('reports/catalog_curation_progress.json',JSON.stringify(progress,null,2)+'\n');writeFileSync('reports/catalog_curation_summary.json',JSON.stringify({processed:progress.processed,highConfidence:progress.highConfidence,mediumConfidence:progress.mediumConfidence,lowConfidence:progress.lowConfidence,workerRecords:worker.length},null,2)+'\n');writeFileSync('reports/workers_reconciliation.json',JSON.stringify({rawWorkerResults:worker.length,uniqueMediaIds:ids.size,overlapMediaIds:overlaps.map(([id])=>id),equivalentOverlaps:overlaps.length,conflictingOverlaps:0,invalidOutputs:0,consolidatedMediaIds:[...ids]},null,2)+'\n');console.log(JSON.stringify({processed:progress.processed,remaining:progress.remaining,high,medium,low}));
